[package]
name = "day20"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day20"
path = "src/main.rs"

[dependencies]
sscanf = "0.4"
itertools = "0.10.5"
num-derive = "0.3"
num-traits = "0.2"
strum="0.24"
strum_macros="0.24"