[package]
name = "day12"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day12"
path = "src/main.rs"

[dependencies]
sscanf = "0.4"
itertools = "0.10.5"
petgraph = "0.6"
serde_json = "1.0"
priority-queue = "1.3"